name: Build conan-vs-extension

on:
  push:
    branches: [ develop2 ]
  pull_request:
    branches: [ develop2 ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet
        run: nuget restore
      - name: Build conan-vs-extension
        run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal
      - uses: actions/upload-artifact@v4
        with:
          name: conan-vs-extension.vsix
          path: bin\Release\conan-vs-extension.vsix
